apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-app-config
  namespace: default
  labels:
    app: flask-app
data:
  FLASK_ENV: "production"
  PORT: "80"
  APP_NAME: "Flask Static Website"
  VERSION: "1.0.0"