apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: flask-app-pdb
  namespace: default
  labels:
    app: flask-app
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: flask-app