apiVersion: v1
kind: ServiceAccount
metadata:
  name: deploy-robot
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::578478003474:role/eks-ecr-access-role # Replace with your IAM role ARN
automountServiceAccountToken: true
imagePullSecrets:
- name: ecr-registry-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: deploy-robot-secret
  namespace: default
  annotations:
    kubernetes.io/service-account.name: deploy-robot
type: kubernetes.io/service-account-token